package constants

var StateNameMap = map[string]bool{
    "Andaman and Nicobar Islands":              true,
    "Andhra Pradesh":                           true,
    "Arunachal Pradesh":                        true,
    "Assam":                                    true,
    "Bihar":                                    true,
    "Chandigarh":                               true,
    "Chhattisgarh":                             true,
    "Dadra and Nagar Haveli and Daman and Diu": true,
    "Delhi":                                    true,
    "Goa":                                      true,
    "Gujarat":                                  true,
    "Haryana":                                  true,
    "Himachal Pradesh":                         true,
    "Jammu and Kashmir":                        true,
    "Jharkhand":                                true,
    "Karnataka":                                true,
    "Kerala":                                   true,
    "Ladakh":                                   true,
    "Lakshadweep":                              true,
    "Madhya Pradesh":                           true,
    "Maharashtra":                              true,
    "Manipur":                                  true,
    "Meghalaya":                                true,
    "Mizoram":                                  true,
    "Nagaland":                                 true,
    "Odisha":                                   true,
    "Puducherry":                               true,
    "Punjab":                                   true,
    "Rajasthan":                                true,
    "Sikkim":                                   true,
    "Tamil Nadu":                               true,
    "Telangana":                                true,
    "Tripura":                                  true,
    "Uttar Pradesh":                            true,
    "Uttarakhand":                              true,
    "West Bengal":                              true,
}